config-version: ${version} # change this and you are dead

# Data storage method. Can either be MySQL ("mysql") or SQLite ("sqlite"). 
# Doesn't do anything for now, its gonna be mysql anyway
storage-method: mysql

# Config for MySQL
# If using SQLite, ignore this
mysql-config: 
    path: "localhost"
    username: "root"
    password: "" # <- this is important
    name: "rdmap"

# Web server configs
webserver: 
    enabled: true
    host: "localhost"
    port: 8080