name: roadmap
version: '0.0.3'
main: me.nusimucat.roadmap.Roadmap
api-version: '1.20'
description: Road Map Plugin for Minecraft

commands:
  roadmap: 
    description: "Roadmap command"
    usage: "tbh i dont really know"
    aliases: [rdm]